GET localhost:80/api/requestStatistic
Content-Type: application/json

{
  "cutUrl": "g"
}

###

POST localhost:80/api/url
Content-Type: application/json

{
  "cutUrl": "r",
  "fullUrl": "rabmler.ru",
  "liveTime": "07-01-2022 11:10:09"
}

